name: PR Close

on:
  pull_request:
    types: [closed]
concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: false
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write
jobs:
  stack-prefix:
    name: Stack Prefix
    uses: ./.github/workflows/.stack-prefix.yml
  cleanup:
    name: Cleanup
    needs: stack-prefix
    environment: tools # if PR plan is used in different environments, cleanup should be done in that environment where the state is stored
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Delete the terraform state files for the PR
        shell: bash
        run: |
          echo "BACKEND_RESOURCE_GROUP=${{ secrets.VNET_RESOURCE_GROUP_NAME }}" >> "$GITHUB_ENV"
          echo "BACKEND_STORAGE_ACCOUNT=${{ vars.STORAGE_ACCOUNT_NAME }}" >> "$GITHUB_ENV"
          echo "BACKEND_CONTAINER_NAME=tfstate" >> "$GITHUB_ENV"
          echo "BACKEND_STATE_KEY=${{ needs.stack-prefix.outputs.stack_prefix }}/${{ github.event.number }}/terraform.tfstate" >> "$GITHUB_ENV"

          echo "checking state file: $BACKEND_STATE_KEY"
          FILE_EXISTS=$(az storage blob exists --container-name ${BACKEND_CONTAINER_NAME} --name "$BACKEND_STATE_KEY" --account-name ${BACKEND_STORAGE_ACCOUNT} --query exists --output tsv)
          echo "File exists: $FILE_EXISTS"
          if [ "$FILE_EXISTS" != "true" ]; then
            echo "State file does not exist, skipping deletion."
          fi
          echo "Deleting state file: $BACKEND_STATE_KEY"
          az storage blob delete --container-name ${BACKEND_CONTAINER_NAME} --name "$BACKEND_STATE_KEY" --account-name ${BACKEND_STORAGE_ACCOUNT} || echo "State file not found, skipping."
          echo "Deleting the folder in the container if empty: ${{ needs.stack-prefix.outputs.stack_prefix }}/${{ github.event.number }}/"
          FOLDER_EXISTS=$(az storage directory exists --name "${{ needs.stack-prefix.outputs.stack_prefix }}/${{ github.event.number }}" --account-name ${BACKEND_STORAGE_ACCOUNT})
          echo "Folder exists: $FOLDER_EXISTS"
          if [ "$FOLDER_EXISTS" = "true" ]; then
            az storage directory delete --name "${{ needs.stack-prefix.outputs.stack_prefix }}/${{ github.event.number }}" --account-name ${BACKEND_STORAGE_ACCOUNT} || echo "Directory not found or not empty, skipping."
          else
            echo "Directory does not exist, skipping."
          fi
